version: "3"

services:
  app:
    build: ./docker/php-fpm
    ports:
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: project
      MYSQL_PASSWORD: project
      MYSQL_DATABASE: project
