version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./www:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - .docker/data:/var/lib/mysql
    environment:
      MYSQL_USER: project
      MYSQL_PASSWORD: project
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: toor

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
